if(NOT DEFINED OPENMETA_VERSION_FILE)
  message(FATAL_ERROR "Missing configured OpenMeta version file")
endif()
set(PACKAGE_FIND_VERSION "0.4.142")
set(PACKAGE_FIND_VERSION_MAJOR 0)
set(PACKAGE_FIND_VERSION_MINOR 4)
set(PACKAGE_FIND_VERSION_PATCH 142)
include("${OPENMETA_VERSION_FILE}")
if(PACKAGE_VERSION_COMPATIBLE)
  message(FATAL_ERROR "The 0.8 SDK accepted a pre-0.5 package request")
endif()
set(PACKAGE_FIND_VERSION "0.5.0")
set(PACKAGE_FIND_VERSION_MAJOR 0)
set(PACKAGE_FIND_VERSION_MINOR 5)
set(PACKAGE_FIND_VERSION_PATCH 0)
include("${OPENMETA_VERSION_FILE}")
if(PACKAGE_VERSION_COMPATIBLE)
  message(FATAL_ERROR "The 0.8 SDK accepted an ABI-incompatible 0.5.0 package request")
endif()
set(PACKAGE_FIND_VERSION "0.5.14")
set(PACKAGE_FIND_VERSION_PATCH 14)
include("${OPENMETA_VERSION_FILE}")
if(PACKAGE_VERSION_COMPATIBLE)
  message(FATAL_ERROR "The 0.8 SDK accepted an ABI-incompatible 0.5.14 package request")
endif()
set(PACKAGE_FIND_VERSION "0.6.0")
set(PACKAGE_FIND_VERSION_MINOR 6)
set(PACKAGE_FIND_VERSION_PATCH 0)
include("${OPENMETA_VERSION_FILE}")
if(PACKAGE_VERSION_COMPATIBLE)
  message(FATAL_ERROR "The 0.8 SDK accepted a different-minor 0.6.0 package request")
endif()
set(PACKAGE_FIND_VERSION "0.6.2")
set(PACKAGE_FIND_VERSION_PATCH 2)
include("${OPENMETA_VERSION_FILE}")
if(PACKAGE_VERSION_COMPATIBLE)
  message(FATAL_ERROR "The 0.8 SDK accepted a different-minor 0.6.2 package request")
endif()
set(PACKAGE_FIND_VERSION "0.7.0")
set(PACKAGE_FIND_VERSION_MINOR 7)
set(PACKAGE_FIND_VERSION_PATCH 0)
include("${OPENMETA_VERSION_FILE}")
if(PACKAGE_VERSION_COMPATIBLE)
  message(FATAL_ERROR "The 0.8 SDK accepted a different-minor 0.7.0 package request")
endif()
set(PACKAGE_FIND_VERSION "0.7.2")
set(PACKAGE_FIND_VERSION_PATCH 2)
include("${OPENMETA_VERSION_FILE}")
if(PACKAGE_VERSION_COMPATIBLE)
  message(FATAL_ERROR "The 0.8 SDK accepted a different-minor 0.7.2 package request")
endif()
set(PACKAGE_FIND_VERSION "0.8.0")
set(PACKAGE_FIND_VERSION_MINOR 8)
set(PACKAGE_FIND_VERSION_PATCH 0)
include("${OPENMETA_VERSION_FILE}")
if(NOT PACKAGE_VERSION_COMPATIBLE)
  message(FATAL_ERROR "The 0.8 SDK rejected a same-minor 0.8.0 package request")
endif()
set(PACKAGE_FIND_VERSION "${PACKAGE_VERSION}")
string(REPLACE "." ";" _openmeta_version_parts "${PACKAGE_FIND_VERSION}")
list(GET _openmeta_version_parts 0 PACKAGE_FIND_VERSION_MAJOR)
list(GET _openmeta_version_parts 1 PACKAGE_FIND_VERSION_MINOR)
list(GET _openmeta_version_parts 2 PACKAGE_FIND_VERSION_PATCH)
include("${OPENMETA_VERSION_FILE}")
if(NOT PACKAGE_VERSION_COMPATIBLE OR NOT PACKAGE_VERSION_EXACT)
  message(FATAL_ERROR "The SDK rejected its exact package version")
endif()
if(NOT OPENMETA_ABI STREQUAL "4")
  message(FATAL_ERROR "Expected the unfrozen development ABI label to remain 4")
endif()
