if(NOT DEFINED OPENMETA_VERSION_FILE OR NOT DEFINED OPENMETA_VERSION)
  message(FATAL_ERROR "Missing configured OpenMeta version information")
endif()

function(check_minimum_version requested compatible exact)
  set(PACKAGE_FIND_VERSION "${requested}")
  string(REPLACE "." ";" version_parts "${requested}")
  list(GET version_parts 0 PACKAGE_FIND_VERSION_MAJOR)
  list(GET version_parts 1 PACKAGE_FIND_VERSION_MINOR)
  list(GET version_parts 2 PACKAGE_FIND_VERSION_PATCH)
  include("${OPENMETA_VERSION_FILE}")
  if(compatible AND NOT PACKAGE_VERSION_COMPATIBLE)
    message(FATAL_ERROR "OpenMeta ${OPENMETA_VERSION} rejected minimum ${requested}")
  elseif(NOT compatible AND PACKAGE_VERSION_COMPATIBLE)
    message(FATAL_ERROR "OpenMeta ${OPENMETA_VERSION} accepted future minimum ${requested}")
  endif()
  if(exact AND NOT PACKAGE_VERSION_EXACT)
    message(FATAL_ERROR "OpenMeta ${OPENMETA_VERSION} rejected its exact version")
  elseif(NOT exact AND PACKAGE_VERSION_EXACT)
    message(FATAL_ERROR "OpenMeta ${OPENMETA_VERSION} claimed an exact match for ${requested}")
  endif()
endfunction()

# Minimum feature requests may cross minor releases; exact requests may not.
foreach(requested IN ITEMS 0.4.142 0.5.0 0.5.14 0.6.0 0.6.2 0.7.0 0.7.2)
  check_minimum_version("${requested}" TRUE FALSE)
endforeach()
check_minimum_version("${OPENMETA_VERSION}" TRUE TRUE)

string(REPLACE "." ";" version_parts "${OPENMETA_VERSION}")
list(GET version_parts 0 version_major)
list(GET version_parts 1 version_minor)
list(GET version_parts 2 version_patch)
math(EXPR next_patch "${version_patch} + 1")
math(EXPR next_minor "${version_minor} + 1")
math(EXPR next_major "${version_major} + 1")
check_minimum_version("${version_major}.${version_minor}.${next_patch}" FALSE FALSE)
check_minimum_version("${version_major}.${next_minor}.0" FALSE FALSE)
check_minimum_version("${next_major}.0.0" FALSE FALSE)

if(NOT OPENMETA_ABI STREQUAL "4")
  message(FATAL_ERROR "Expected the unfrozen development ABI label to remain 4")
endif()
